version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet-runtime:
        patterns: ["Microsoft.*", "System.*", "Npgsql*"]
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]
  - package-ecosystem: terraform
    directory: /infra/terraform/aws-runtime
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
